service: race-tracker-api


provider:
  name: aws
  runtime: nodejs8.10 
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions:

  getEvent:
    handler: handler.getEvent
    events:
      - http:
          path: data/event
          method: get
          cors: true
          
  #creates an Event
  createEvent:
    handler: handler.createEvent # point to exported create function in handler.js
    events:
      - http:
          path: data/event 
          method: post
          cors: true

  deleteEvent:
    handler: handler.deleteEvent
    events:
      - http:
          path: data/event/
          method: delete
          cors: true

  getRunners:
    handler: handler.getRunners
    events:
      - http:
          path: data/runners
          method: get
          cors: true

  createRunners:
    handler: handler.createRunners
    events:
      - http:
          path: data/runners
          method: post
          cors: true

  #updates event, then removes runners from database
  removeRunners:
    handler: handler.deleteRunners
    events: 
      - http:   
          path: data/runners
          method: put
          cors: true

  getAll:
    handler: handler.getAll
    events:
      - http:
          path: data/ # path will be domain.name.com/dev/notes/1
          method: get
          cors: true

  deleteAll:
    handler: handler.deleteAll
    events:
      - http:
          path: data/ # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true     

  addHeats:
    handler: handler.addHeats
    events:
      - http:
          path: data/event/heats/add
          method: put
          cors: true     

  removeHeats:
    handler: handler.removeHeats
    events:
      - http:
          path: data/event/heats/remove
          method: put
          cors: true

  addCheckpoints:
    handler: handler.addCheckpoints
    events:
      - http:
          path: data/event/checkpoints/add
          method: put
          cors: true

  removeCheckpoints:
    handler: handler.removeCheckpoints
    events:
      - http:
          path: data/event/checkpoints/remove
          method: put
          cors: true

  addSplits:
    handler: handler.addSplits
    events:
      - http:
          path: data/runner/splits/add
          method: put
          cors: true
    
  startHeat:
    handler: handler.startHeat
    events:
      - http:
          path: data/event/heats/start
          method: put
          cors: true
          
plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation